/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNKSt12__shared_ptrIN5torch2nn10LinearImplELN9__gnu_cxx12_Lock_policyE2EEcvbEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZNKSt12__shared_ptrIN5torch2nn10LinearImplELN9__gnu_cxx12_Lock_policyE2EEcvbEv.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter(log, args, state) {
    var fnSym = findFnDbgSym(this.context.pc)
    log(`在OnEnter中获得本函数的fnSym=${JSON.stringify(fnSym)}`)
    //在frida-trace所生成的js脚本的OnEnter中： this.context.pc == onEnter所拦截的函数地址
    log(`[simple_nn.elf] ${this.context.pc}`); // 
  },

  /**
   * Called synchronously when about to return from _ZNKSt12__shared_ptrIN5torch2nn10LinearImplELN9__gnu_cxx12_Lock_policyE2EEcvbEv.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave(log, retval, state) {
  }
}
